### ISSUE TITLE
Plugin fails on load

### ISSUE THREAD

**Issue by jordguitar** [goaaats/universalis_act_plugin#1]
```
{"PlayerSetup":399,"MarketBoardItemRequestStart":315,"MarketBoardOfferings":316,"MarketBoardHistory":320}
[ERROR] Could not initialize plugin:
System.InvalidCastException: [A]FFXIV_ACT_Plugin.FFXIV_ACT_Plugin cannot be cast to [B]FFXIV_ACT_Plugin.FFXIV_ACT_Plugin. Type A originates from 'FFXIV_ACT_Plugin, Version=2.0.4.0, Culture=neutral, PublicKeyToken=null' in the context 'LoadNeither' in a byte array. Type B originates from 'FFXIV_ACT_Plugin, Version=2.0.4.0, Culture=neutral, PublicKeyToken=null' in the context 'Default' at location 'D:\ACT\FFXIV_ACT_Plugin.dll'.
   at UniversalisPlugin.PluginSample.GetFfxivPlugin()
   at UniversalisPlugin.PluginSample.InitPlugin(TabPage pluginScreenSpace, Label pluginStatusText)
```

**Comment by goaaats** [comment]
Will push a fix tonight, thanks

**Comment by Val870** [comment]
I have the same issue ^^'
I guess it is solved in https://github.com/goaaats/universalis_act_plugin/pull/2. 

When do you plan to release it ?

**Comment by Val870** [comment]
Nevermind, you just released it: https://github.com/goaaats/universalis_act_plugin/releases/tag/1.1

Should I open an issue for the not displaying commits diff on the release 1.1 or is it just a human mistake @goaaats ?
