### ISSUE TITLE
"Unhandled Exception in ACT"

### ISSUE THREAD

**Issue by Honobe** [goaaats/universalis_act_plugin#32]
System.NullReferenceException - Object reference not set to an instance of an object.
   at RainbowMage.OverlayPlugin.NewOverlayDialog.cbPreset_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

RainbowMage.OverlayPlugin.NewOverlayDialog, OverlayPlugin.Core, Version=0.16.6.0, Culture=neutral, PublicKeyToken=null

This is what I get when I load ACT with the addon. I put the addon in the addons folder for ACT and it doesn't seem to want to load.

**Comment by Honobe** [comment]
I think that may have been my fault. I forgot to add it in the ACT launcher itself.
