### ISSUE TITLE
Fatal Error - Unhandled Exception

### ISSUE THREAD

**Issue by Webberjo** [goaaats/universalis_act_plugin#5]
Attempting to initialize this plugin sometimes causes the following fatal error to crash ACT:
```
---------------------------
Fatal Error - Unhandled Exception
---------------------------
An unhandled exception has occurred.  ACT may close.
Press Ctrl-C to copy this MessageBox.

System.Reflection.TargetInvocationException - Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)

   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)

   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at FFXIV_ACT_Plugin.Memory.DataSubscription.DelegateCallback(IAsyncResult ar)

   at System.Runtime.Remoting.Messaging.AsyncResult.SyncProcessMessage(IMessage msg)

   at System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage(IMessage msg, IMessageSink replySink)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

System.RuntimeMethodHandle, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
---------------------------
OK   
---------------------------
```
Furthermore, I can't see to get this plugin to upload anything anymore since patch 5.1 was released.
I'm currently using FFXIV_ACT_Plugin v2.0.4.2

**Comment by agate-pris** [comment]
I've get same error.

**Comment by Krude** [comment]
I get the same error, and it crashes my ACT in the process, but it's not on loading, but randomly when checking MB prices.
